### ISSUE TITLE
[spike] test out 15, 20 frames per sample if it performs better than 10

### ISSUE THREAD

**Issue by AgiliaErnis** [AgiliaErnis/asl-validator#29]
### Background research, bigger frames:
- a) longer processing time (tested different ranges between 25-35 frames)
- b) low ~0.3 accuracy 
- c) or vise versa ~1.0 accuracy on paper, but very low precision on real-time testing also due to too similar data set (tried using similar angles and background) ended up with overfitted model

**So, based on this:**
- bigger training samples (started from 30 > 40 > 50, currently at 100 videos per sign)
- smaller number of frames (currently at 10 frames)

### Todo:
- [ ] gather and test performance on the next triplet with 15 frames
- [ ] gather and test performance on the  triplet after that with 15 frames
- [ ] compare findings with 10 frame trained model
- [ ] update [[story] capture 25% of ASL alphabet signs #12](https://github.com/AgiliaErnis/asl-validator/issues/12) based on the conclusion
